

# Spark does not work with alpine version
# UnsatisfiedLinkError /tmp/snappy-unknown-4324a351-29e8-4c89-8305-5bf8d05168cf-libsnappyjava.so: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /tmp/snappy-unknown-4324a351-29e8-4c89-8305-5bf8d05168cf-libsnappyjava.so) java.lang.ClassLoader$NativeLibrary.load (ClassLoader.java:-2)
